"""Build the documentation site, generating the example pages on the fly.

great-docs renders ``.qmd``/``.md`` files as documentation pages but does not
render Jupyter notebooks directly, and it only stages a section's ``.qmd`` pages
and asset *subdirectories* into its build tree (never a loose top-level
notebook). Each notebook in ``docs/examples/`` is therefore shown through a thin
``.qmd`` wrapper that embeds the notebook's stored outputs from a transient
``_src/`` subdirectory.

The section index that great-docs auto-generates renders pages as image cards
when their front matter carries ``description`` and ``image`` fields, so each
wrapper also gets a card description (the notebook's ``metadata.description``,
falling back to the first sentence of its intro paragraph) and a thumbnail PNG
extracted from the notebook's stored outputs into a transient ``thumbnails/``
subdirectory (the first figure of the cell tagged ``thumbnail``, falling back
to the first figure in the notebook).

All of that is pure boilerplate derived from the notebooks, so instead of
committing it we generate it just before building and remove it again afterwards
(even if the build fails). The notebooks themselves stay in ``docs/examples/``.

The multi-version site is derived at build time, so releases need no docs
steps: the newest semver git tag becomes the stable site root and this checkout
becomes ``/v/dev/``. The tag's API snapshot (used by great-docs to prune the
stable reference to the released API) is generated on demand into the
gitignored ``.great-docs-cache/`` via ``scripts/api_snapshot.py``, and the
corresponding ``versions:`` block is injected into ``great-docs.yml`` for the
duration of the build (great-docs has no config override mechanism) and
restored afterwards, even on failure. Only a hard kill can leave the file
patched; ``git restore great-docs.yml`` fixes that.

After a successful ``build``, the ``/v/latest/`` and ``/v/stable/`` alias
redirects of the versioned site are rewritten to absolute URLs: great-docs
writes them with root-relative targets, which on a GitHub Pages project site
escape the ``/numpyro_forecast/`` prefix.

Usage:

```bash
python scripts/build_docs.py build      # generate, build, clean up
python scripts/build_docs.py preview    # same, but serve with live reload
```
"""

import base64
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "docs" / "examples"
# Notebooks are copied here at build time so great-docs stages them for the
# embed shortcode; the leading underscore stops Quarto rendering them as pages.
EMBED_DIR = EXAMPLES_DIR / "_src"
# Card thumbnails extracted from the notebooks' stored outputs; great-docs
# stages the whole directory as a section asset.
THUMBNAILS_DIR = EXAMPLES_DIR / "thumbnails"
# Notebook headings follow "<Title> with `numpyro_forecast`"; drop the suffix.
TITLE_SUFFIX = " with `numpyro_forecast`"
# Cell tag marking the figure to use as the notebook's index-card thumbnail.
THUMBNAIL_TAG = "thumbnail"
# Site config (source of `site_url`) and the built site with the /v/<alias>/
# redirect stubs that need absolute targets on a GitHub Pages project site.
REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "great-docs.yml"
SITE_DIR = REPO_ROOT / "great-docs" / "_site"
ALIAS_STUBS = ("latest", "stable")
# Build-time versioning: release snapshots are cached here (tags are immutable,
# so a cached snapshot never goes stale) and generated by this sibling script.
CACHE_SNAPSHOT_DIR = REPO_ROOT / ".great-docs-cache" / "api-snapshots"
API_SNAPSHOT_SCRIPT = Path(__file__).resolve().parent / "api_snapshot.py"
# Release tags are bare semver (see AGENTS.md / release.yml).
SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def load_notebook(path: Path) -> dict[str, Any]:
    """Load a notebook's JSON document.

    Parameters
    ----------
    path
        Path to the ``.ipynb`` file.

    Returns
    -------
    dict[str, Any]
        The parsed notebook document.
    """
    return json.loads(path.read_text(encoding="utf-8"))


def notebook_title(notebook: dict[str, Any], path: Path) -> str:
    """Derive a page title from a notebook's first level-1 heading.

    Parameters
    ----------
    notebook
        The parsed notebook document.
    path
        Path to the ``.ipynb`` file, used as a fallback title source.

    Returns
    -------
    str
        The first markdown ``# `` heading with the trailing
        ``" with `numpyro_forecast`"`` suffix removed, or a title derived from
        the file name when no heading is found.
    """
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", []))
        for line in source.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                if title.endswith(TITLE_SUFFIX):
                    title = title[: -len(TITLE_SUFFIX)]
                return title
    return path.stem.replace("_", " ").capitalize()


def _strip_markdown(text: str) -> str:
    """Reduce inline markdown to plain text for use in raw HTML.

    Parameters
    ----------
    text
        Markdown text.

    Returns
    -------
    str
        The text with links reduced to their label and emphasis/code markers
        removed (great-docs injects card descriptions into HTML unescaped).
    """
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    return text.replace("**", "").replace("`", "").replace("*", "")


def _intro_first_sentence(notebook: dict[str, Any]) -> str:
    """Extract the first sentence of the intro paragraph after the H1 heading.

    Parameters
    ----------
    notebook
        The parsed notebook document.

    Returns
    -------
    str
        The first sentence of the first non-heading paragraph in the first
        markdown cell, stripped of inline markdown, or ``""`` if none exists.
    """
    for cell in notebook.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        source = "".join(cell.get("source", []))
        for paragraph in re.split(r"\n\s*\n", source):
            paragraph = " ".join(paragraph.split())
            if not paragraph or paragraph.startswith("#"):
                continue
            sentence = re.split(r"(?<=[.!?])\s", _strip_markdown(paragraph), maxsplit=1)[0]
            return sentence.strip()
        return ""
    return ""


def notebook_description(notebook: dict[str, Any]) -> str:
    """Derive the index-card description for a notebook.

    Parameters
    ----------
    notebook
        The parsed notebook document.

    Returns
    -------
    str
        The notebook's ``metadata.description`` if set (plain text by
        convention: great-docs injects it into HTML unescaped), otherwise the
        first sentence of the intro paragraph, or ``""`` if neither exists.
    """
    description = notebook.get("metadata", {}).get("description", "")
    if description:
        return str(description).strip()
    return _intro_first_sentence(notebook)


def _cell_image(cell: dict[str, Any]) -> str | None:
    """Return the base64 payload of a cell's first PNG output.

    Parameters
    ----------
    cell
        A notebook cell.

    Returns
    -------
    str | None
        The base64-encoded PNG (nbformat stores it as a string or a list of
        strings), or ``None`` if the cell has no PNG output.
    """
    for output in cell.get("outputs", []):
        png = output.get("data", {}).get("image/png")
        if png is not None:
            return "".join(png) if isinstance(png, list) else png
    return None


def extract_thumbnail(notebook: dict[str, Any], dest: Path) -> bool:
    """Write a notebook's thumbnail figure to ``dest``.

    Uses the first PNG output of the first cell tagged ``thumbnail``, falling
    back to the first PNG output in the notebook.

    Parameters
    ----------
    notebook
        The parsed notebook document.
    dest
        Path of the PNG file to write.

    Returns
    -------
    bool
        ``True`` if a figure was found and written, ``False`` otherwise (the
        page then falls back to great-docs' plain link list).
    """
    cells = [c for c in notebook.get("cells", []) if c.get("cell_type") == "code"]
    tagged = [c for c in cells if THUMBNAIL_TAG in c.get("metadata", {}).get("tags", [])]
    for cell in [*tagged, *cells]:
        payload = _cell_image(cell)
        if payload is not None:
            dest.write_bytes(base64.b64decode(payload))
            return True
    return False


def generate_pages() -> list[Path]:
    """Stage the notebooks and write a ``.qmd`` wrapper for each.

    Returns
    -------
    list[pathlib.Path]
        The wrapper files that were created (the ``_src/`` and ``thumbnails/``
        directories are removed wholesale by `clean_pages()`).
    """
    EMBED_DIR.mkdir(exist_ok=True)
    THUMBNAILS_DIR.mkdir(exist_ok=True)
    created: list[Path] = []
    for path in sorted(EXAMPLES_DIR.glob("*.ipynb")):
        notebook = load_notebook(path)
        shutil.copy2(path, EMBED_DIR / path.name)
        front_matter = [f"title: {json.dumps(notebook_title(notebook, path))}"]
        description = notebook_description(notebook)
        if description:
            front_matter.append(f"description: {json.dumps(description)}")
        if extract_thumbnail(notebook, THUMBNAILS_DIR / f"{path.stem}.png"):
            front_matter.append(f"image: thumbnails/{path.stem}.png")
        wrapper = EXAMPLES_DIR / f"{path.stem}.qmd"
        wrapper.write_text(
            "---\n"
            + "\n".join(front_matter)
            + f"\n---\n\n{{{{< embed _src/{path.name} echo=true >}}}}\n",
            encoding="utf-8",
        )
        created.append(wrapper)
    return created


def clean_pages(wrappers: list[Path]) -> None:
    """Delete generated wrappers and the transient ``_src``/``thumbnails`` copies.

    Parameters
    ----------
    wrappers
        Wrapper files to remove.
    """
    for wrapper in wrappers:
        wrapper.unlink(missing_ok=True)
    shutil.rmtree(EMBED_DIR, ignore_errors=True)
    shutil.rmtree(THUMBNAILS_DIR, ignore_errors=True)


def newest_semver(tags: list[str]) -> str | None:
    """Pick the newest bare-semver tag.

    Parameters
    ----------
    tags
        Candidate tag names; non-semver entries (``v1.0``, ``foo``) are ignored.

    Returns
    -------
    str | None
        The highest version by numeric comparison, or ``None`` when no tag
        matches ``MAJOR.MINOR.PATCH``.
    """
    releases = [tag for tag in tags if SEMVER_RE.match(tag)]
    if not releases:
        return None
    return max(releases, key=lambda tag: tuple(int(part) for part in tag.split(".")))


def latest_release_tag() -> str | None:
    """Return the newest release tag of this repository.

    Returns
    -------
    str | None
        The newest bare-semver git tag, or ``None`` when the clone has no
        release tags (e.g. a fork), in which case the site builds unversioned.
    """
    result = subprocess.run(
        ["git", "tag", "--list"],  # noqa: S607
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return newest_semver(result.stdout.split())


def ensure_release_snapshot(tag: str) -> Path:
    """Return the API snapshot for a release tag, generating it if needed.

    The snapshot records which ``reference:`` entries resolve in the released
    package; great-docs uses it to prune the stable reference pages. It is
    generated by resolving the current reference config against a temporary
    worktree of the tag, and cached under ``.great-docs-cache/`` (tags are
    immutable, so an existing file is always current). Generation failures
    propagate: without the snapshot great-docs would silently skip pruning.

    Parameters
    ----------
    tag
        The release tag to snapshot.

    Returns
    -------
    pathlib.Path
        Path to the snapshot JSON, inside the repo so great-docs can resolve
        it relative to the project root.
    """
    dest = CACHE_SNAPSHOT_DIR / f"{tag}.json"
    if dest.exists():
        return dest
    worktree = Path(tempfile.mkdtemp(prefix=f"nf-docs-{tag}-"))
    try:
        subprocess.run(  # noqa: S603
            ["git", "worktree", "add", "--detach", str(worktree), tag],  # noqa: S607
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        )
        subprocess.run(  # noqa: S603
            [
                sys.executable,
                str(API_SNAPSHOT_SCRIPT),
                "--package-root",
                str(worktree),
                "--output",
                str(dest),
            ],
            check=True,
        )
    finally:
        subprocess.run(  # noqa: S603
            ["git", "worktree", "remove", "--force", str(worktree)],  # noqa: S607
            cwd=REPO_ROOT,
            check=False,
            capture_output=True,
        )
        # If `git worktree add` itself failed, the directory was never a
        # registered worktree, so the remove above cannot delete it.
        shutil.rmtree(worktree, ignore_errors=True)
    return dest


def inject_versions(config_text: str, tag: str, snapshot_relpath: str) -> str:
    """Add the build-time ``versions:`` block to the great-docs config.

    Parameters
    ----------
    config_text
        The original ``great-docs.yml`` contents.
    tag
        The newest release tag; it becomes the ``latest`` entry (site root).
    snapshot_relpath
        The release's API snapshot path, relative to the repo root.

    Returns
    -------
    str
        The config with ``versions:`` set to the dev (this checkout, rendered
        at ``/v/dev/``) and release entries, newest first as great-docs expects.
    """
    config = yaml.safe_load(config_text)
    config["versions"] = [
        {"label": "dev", "tag": "dev", "prerelease": True},
        {"label": tag, "tag": tag, "latest": True, "api_snapshot": snapshot_relpath},
    ]
    return yaml.safe_dump(config, sort_keys=False)


def fix_alias_redirects(site_dir: Path, site_url: str) -> None:
    """Point the ``/v/latest/`` and ``/v/stable/`` alias redirects at the site root.

    great-docs writes these alias stubs with root-relative targets (``/``),
    which on a GitHub Pages project site resolve to ``juanitorduz.github.io/``
    instead of the site. Both aliases target the root, which serves the latest
    release.

    Parameters
    ----------
    site_dir
        The built ``_site`` directory.
    site_url
        Absolute URL of the deployed site root.
    """
    target = site_url if site_url.endswith("/") else f"{site_url}/"
    for name in ALIAS_STUBS:
        stub = site_dir / "v" / name / "index.html"
        if not stub.exists():
            continue
        stub.write_text(
            "<!DOCTYPE html>\n"
            '<html lang="en">\n'
            "<head>\n"
            '  <meta charset="utf-8">\n'
            f'  <meta http-equiv="refresh" content="0; url={target}">\n'
            f'  <link rel="canonical" href="{target}">\n'
            "  <title>Redirecting…</title>\n"
            "</head>\n"
            "<body>\n"
            f'  <p>Redirecting to <a href="{target}">{target}</a>…</p>\n'
            "</body>\n"
            "</html>\n",
            encoding="utf-8",
        )


def main() -> int:
    """Generate pages, run the requested great-docs command, then clean up.

    Returns
    -------
    int
        The exit code of the great-docs command.
    """
    command = sys.argv[1] if len(sys.argv) > 1 else "build"
    wrappers = generate_pages()
    original_config = CONFIG_PATH.read_text(encoding="utf-8")
    patched = False
    try:
        tag = latest_release_tag()
        if tag is None:
            print("No release tag found; building an unversioned site.")
        else:
            snapshot = ensure_release_snapshot(tag)
            relpath = snapshot.relative_to(REPO_ROOT).as_posix()
            CONFIG_PATH.write_text(
                inject_versions(original_config, tag, relpath), encoding="utf-8"
            )
            patched = True
        code = subprocess.run(["great-docs", command], check=False).returncode  # noqa: S603, S607
        if code == 0 and command == "build":
            config = yaml.safe_load(original_config)
            fix_alias_redirects(SITE_DIR, config["site_url"])
        return code
    finally:
        clean_pages(wrappers)
        if patched:
            CONFIG_PATH.write_text(original_config, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
